version: 2
updates:
  - package-ecosystem: "docker-compose"
    directories:
      - "/arr"
      - "/beszel"
      - "/caddy"
      - "/cups"
      - "/filebrowser"
      - "/jellyfin"
      - "/pihole"
      - "/qbittorrent"
      - "/seerr"
      - "/tailscale"
      - "/tailscale-dns"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directories:
      - "/caddy"
      - "/pihole/pihole-dns-shim"
      - "/tailscale-dns"
    schedule:
      interval: "daily"
