x-warnings: # A block to avoid repeating the same warnings.
  - ${PORKBUN_API_KEY:?Porkbun API key not set}
  - ${PORKBUN_API_SECRET_KEY:?Porkbun API secret key not set}
  - ${DOMAIN_NAME:?Domain name not set}

services:
  caddy:
    #image: lucaslorentz/caddy-docker-proxy:ci-alpine
    build: .
    container_name: caddy
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp
    environment:
      CADDY_INGRESS_NETWORKS: caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
    labels:
      # caddy.acme_ca: https://acme-staging-v02.api.letsencrypt.org/directory
      caddy.acme_dns: porkbun
      caddy.acme_dns.api_key: $PORKBUN_API_KEY
      caddy.acme_dns.api_secret_key: $PORKBUN_API_SECRET_KEY
      # Health check
      caddy_0: http://localhost:12345
      caddy_0.respond: /health "OK" 200
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:12345/health"]
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3
  whoami:
    image: traefik/whoami
    networks:
      - caddy
    environment:
      WHOAMI_PORT_NUMBER: 4444
    labels:
      caddy: whoami.$DOMAIN_NAME
      caddy.reverse_proxy: "{{upstreams 4444}}"

networks:
  caddy:
    external: true

volumes:
  caddy_data:
