x-warnings: # A block to avoid repeating the same warnings.
  - ${DOMAIN_NAME:?DOMAIN_NAME must be set}
  - ${MEDIA_ROOT:?MEDIA_ROOT must be set}

services:
  beszel:
    image: henrygd/beszel:0.18
    container_name: beszel
    ports:
      - 8090:8090
    environment:
      APP_URL: http://dash.$DOMAIN_NAME # NOTE: this will be included in any emails sent
      AUTO_LOGIN: ${BESZEL_AUTO_LOGIN_EMAIL:-} # explicitly permit empty values
    healthcheck:
      test: ["CMD", "/beszel", "health", "--url", "http://localhost:8090"]
      start_period: 5s
      interval: 120s
    restart: unless-stopped
    volumes:
      - ./beszel_data:/beszel_data
      - beszel_socket:/beszel_socket
    networks:
      - caddy
    labels:
      caddy: dash.$DOMAIN_NAME
      caddy.reverse_proxy: "{{upstreams 8090}}"

  beszel-agent:
    image: henrygd/beszel-agent:0.18
    container_name: beszel-agent
    privileged: true # This can be replaced with `devices: ...` to allow smartctl to run
    cap_add:
      - SYS_RAWIO # required for S.M.A.R.T. data
      - SYS_ADMIN # required for NVMe S.M.A.R.T. data
    depends_on:
      - beszel
    network_mode: host
    environment:
      HUB_URL: http://localhost:8090
      LISTEN: /beszel_socket/beszel.sock
      KEY: $BESZEL_KEY
      TOKEN: $BESZEL_TOKEN
    healthcheck:
      test: ["CMD", "/agent", "health"]
      start_period: 5s
      interval: 120s
    restart: unless-stopped
    volumes:
      - $MEDIA_ROOT/.beszel:/extra-filesystems/sda1__Media Root:ro
      - ./beszel_agent_data:/var/lib/beszel-agent
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro # systemd services
      - /var/run/docker.sock:/var/run/docker.sock:ro # docker containers
      - beszel_socket:/beszel_socket

networks:
  caddy:
    external: true

volumes:
  beszel_socket:
