services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    environment:
      APP_URL: http://localhost:8090
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket
    networks: [caddy]
    labels:
      caddy: dash.${DOMAIN_NAME?DOMAIN_NAME must be set}
      caddy.reverse_proxy: "{{upstreams 8090}}"

  beszel-agent:
    image: henrygd/beszel-agent:alpine
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./beszel_agent_data:/var/lib/beszel-agent
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${MEDIA_ROOT?:MEDIA_ROOT must be set}/.beszel:/extra-filesystems/sda1__Media Root:ro
    privileged: true # This can be replaced with `devices: ...` to allow smartctl to run
    cap_add:
      - SYS_RAWIO # required for S.M.A.R.T. data
      - SYS_ADMIN # required for NVMe S.M.A.R.T. data
    depends_on:
      - beszel
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: http://localhost:8090
      # Explicitly allow empty values for these variables. They should be set after runnig beszel.
      TOKEN: ${BESZEL_TOKEN}
      KEY: ${BESZEL_KEY}

networks:
  caddy:
    external: true
